return {}

-- return {
--   "yetone/avante.nvim",
--   event = "VeryLazy",
--   lazy = false,
--   version = false, -- set this if you want to always pull the latest change
--   opts = {
--     debug = false,
--     ---@alias Provider "claude" | "openai" | "azure" | "gemini" | "cohere" | "copilot" | [string]
--     provider = "gemini", -- Only recommend using Claude
--     auto_suggestions_provider = "claude",
--     ---@type AvanteSupportedProvider
--     claude = {
--       endpoint = "https://api.anthropic.com",
--       model = "claude-3-7-sonnet-20250219",
--       temperature = 0,
--       max_tokens = 4096,
--     },
--     gemini = {
--       model = "gemini-2.5-pro-exp-03-25",
--       temperature = 0,
--       max_tokens = 4096,
--       api_key_name = "GEMINI_API_KEY",
--     },
--     web_search_engine = {
--       provider = "tavily", -- tavily, serpapi, searchapi or google
--     },
--     cursor_applying_provider = 'groq',
--     ---To add support for custom provider, follow the format below
--     ---See https://github.com/yetone/avante.nvim/wiki#custom-providers for more details
--     ---@type {[string]: AvanteProvider}
--     vendors = {
--       ---@type AvanteSupportedProvider
--       ["claude-haiku"] = {
--         endpoint = "https://api.anthropic.com",
--         model = "claude-3-5-haiku-20241022",
--         timeout = 30000, -- Timeout in milliseconds
--         temperature = 0,
--         max_tokens = 8000,
--       },
--       ---@type AvanteSupportedProvider
--       ["claude-opus"] = {
--         endpoint = "https://api.anthropic.com",
--         model = "claude-3-opus-20240229",
--         timeout = 30000, -- Timeout in milliseconds
--         temperature = 0,
--         max_tokens = 8000,
--       },
--       groq = { -- define groq provider
--         __inherited_from = 'openai',
--         api_key_name = 'GROQ_API_KEY',
--         endpoint = 'https://api.groq.com/openai/v1/',
--         model = 'llama-3.3-70b-versatile',
--         max_tokens = 32768, -- remember to increase this value, otherwise it will stop generating halfway
--       },
--     },
--     ---Specify the behaviour of avante.nvim
--     ---1. auto_apply_diff_after_generation: Whether to automatically apply diff after LLM response.
--     ---                                     This would simulate similar behaviour to cursor. Default to false.
--     ---2. auto_set_keymaps                : Whether to automatically set the keymap for the current line. Default to true.
--     ---                                     Note that avante will safely set these keymap. See https://github.com/yetone/avante.nvim/wiki#keymaps-and-api-i-guess for more details.
--     ---3. auto_set_highlight_group        : Whether to automatically set the highlight group for the current line. Default to true.
--     ---4. support_paste_from_clipboard    : Whether to support pasting image from clipboard. This will be determined automatically based whether img-clip is available or not.
--     behaviour = {
--       auto_suggestions = false, -- Experimental stage
--       auto_set_highlight_group = true,
--       auto_set_keymaps = true,
--       auto_apply_diff_after_generation = false,
--       support_paste_from_clipboard = false,
--       minimize_diff = true, -- Whether to remove unchanged lines when applying a code block
--       enable_cursor_planning_mode = true,
--     },
--     history = {
--       max_tokens = 4096,
--       storage_path = vim.fn.stdpath("state") .. "/avante",
--       paste = {
--         extension = "png",
--         filename = "pasted-%Y-%m-%d-%H-%M-%S",
--       },
--     },
--     highlights = {
--       ---@type AvanteConflictHighlights
--       diff = {
--         current = "DiffText",
--         incoming = "DiffAdd",
--       },
--     },
--     mappings = {
--       ---@class AvanteConflictMappings
--       diff = {
--         ours = "co",
--         theirs = "ct",
--         all_theirs = "ca",
--         both = "cb",
--         cursor = "cc",
--         next = "]x",
--         prev = "[x",
--       },
--       suggestion = {
--         accept = "<M-l>",
--         next = "<M-]>",
--         prev = "<M-[>",
--         dismiss = "<C-]>",
--       },
--       jump = {
--         next = "]]",
--         prev = "[[",
--       },
--       submit = {
--         normal = "<CR>",
--         insert = "<C-s>",
--       },
--       -- NOTE: The following will be safely set by avante.nvim
--       ask = "<leader>aa",
--       edit = "<leader>ae",
--       refresh = "<leader>ar",
--       focus = "<leader>af",
--       toggle = {
--         default = "<leader>at",
--         debug = "<leader>ad",
--         hint = "<leader>ah",
--         suggestion = "<leader>as",
--         repomap = "<leader>aR",
--       },
--       sidebar = {
--         apply_all = "A",
--         apply_cursor = "a",
--         switch_windows = "<Tab>",
--         reverse_switch_windows = "<S-Tab>",
--       },
--     },
--     windows = {
--       ---@alias AvantePosition "right" | "left" | "top" | "bottom" | "smart"
--       position = "right",
--       wrap = true, -- similar to vim.o.wrap
--       width = 30, -- default % based on available width in vertical layout
--       height = 30, -- default % based on available height in horizontal layout
--       sidebar_header = {
--         enabled = true, -- true, false to enable/disable the header
--         align = "center", -- left, center, right for title
--         rounded = true,
--       },
--       input = {
--         prefix = "> ",
--         height = 8, -- Height of the input window in vertical layout
--       },
--       edit = {
--         border = "rounded",
--         start_insert = true, -- Start insert mode when opening the edit window
--       },
--       ask = {
--         floating = false, -- Open the 'AvanteAsk' prompt in a floating window
--         border = "rounded",
--         start_insert = true, -- Start insert mode when opening the ask window
--         ---@alias AvanteInitialDiff "ours" | "theirs"
--         focus_on_apply = "ours", -- which diff to focus after applying
--       },
--     },
--     highlights = {
--       ---@type AvanteConflictHighlights
--       diff = {
--         current = "DiffText",
--         incoming = "DiffAdd",
--       },
--     },
--     --- @class AvanteConflictConfig
--     diff = {
--       autojump = true,
--       ---@type string | fun(): any
--       list_opener = "copen",
--       --- Override the 'timeoutlen' setting while hovering over a diff (see :help timeoutlen).
--       --- Helps to avoid entering operator-pending mode with diff mappings starting with `c`.
--       --- Disable by setting to -1.
--       override_timeoutlen = 500,
--     },
--     --- @class AvanteHintsConfig
--     hints = {
--       enabled = false,
--     },
--     suggestion = {
--       debounce = 600,
--       throttle = 600,
--     },
--   },
--   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
--   build = "make",
--   -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
--   dependencies = {
--     "nvim-treesitter/nvim-treesitter",
--     "stevearc/dressing.nvim",
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     --- The below dependencies are optional,
--     "echasnovski/mini.icons", -- or nvim-tree/nvim-web-devicons
--     "zbirenbaum/copilot.lua", -- for providers='copilot'
--     {
--       -- support for image pasting
--       "HakonHarnes/img-clip.nvim",
--       event = "VeryLazy",
--       opts = {
--         -- recommended settings
--         default = {
--           embed_image_as_base64 = false,
--           prompt_for_file_name = false,
--           drag_and_drop = {
--             insert_mode = true,
--           },
--           -- required for Windows users
--           use_absolute_path = true,
--         },
--       },
--     },
--   },
-- }
